var indexList = [
    {
        id:1,
        name:"交通位置",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:7,
                name:"地铁",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:14,
                name:"公交",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:8,
                name:"开车",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:9,
                name:"环线",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:10,
                name:"商圈",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            }
        ]
    },
    {
        id:2,
        name:"动态通勤",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:30,
                name:"公共交通通勤",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:31,
                name:"开车打车通勤",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
        ]
    },
    {
        id:3,
        name:"自然",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:11,
                name:"公园",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:12,
                name:"户均绿化",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:13,
                name:"马路",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:15,
                name:"马路屏蔽",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            }
        ]
    },
    {
        id:4,
        name:"生活便利",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:25,
                name:"餐饮",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:26,
                name:"休闲娱乐",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:27,
                name:"运动健身",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:28,
                name:"生活服务",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:29,
                name:"购物",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:35,
                name:"菜场",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
        ]
    },
    {
        id:5,
        name:"教育",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:17,
                name:"幼儿园",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:18,
                name:"小学",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:19,
                name:"中学",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:20,
                name:"贵族学校",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:21,
                name:"培训机构",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
        ]
    },
    {
        id:6,
        name:"投资",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:32,
                name:"租售比",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:33,
                name:"换手",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:34,
                name:"升值潜力",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },

        ]
    },
    {
        id:16,
        name:"房屋",
        innerValue:1.0,
        rate:1.0,
        totalValue:1.0,
        children:[
            {
                id:22,
                name:"建筑年代指数",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:23,
                name:"开发商指数",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
            {
                id:24,
                name:"物业公司指数",
                innerValue:1.0,
                rate:1.0,
                totalValue:1.0
            },
        ]
    },


];

var tagList = [
    {
        id:1,
        name:"四通八达",
        parent:0,
        factor:{id_1:1.00,id_2:1.00}
    },
    {
        id:2,
        name:"地铁便利",
        parent:1,//跟着id为1
        factor:{id_7:1.00,id_30:1.00}
    },
    {
        id:3,
        name:"公交枢纽",
        parent:1,
        factor:{id_14:1.00,id_30:1.00}
    },
    {
        id:4,
        name:"开车便利",
        parent:1,
        factor:{id_8:1.00,id_31:1.00}
    },
    {
        id:5,
        name:"景观居所",
        parent:0,
        factor:{id_3:1.00}
    },
    {
        id:6,
        name:"临近公园",
        parent:5,
        factor:{id_11:1.00}
    },
    {
        id:7,
        name:"小区绿化好",
        parent:5,
        factor:{id_12:1.00}
    },
    {
        id:8,
        name:"运动爱好者",
        parent:5,
        factor:{id_12:1.00,id_27:1.00}
    },
    {
        id:9,
        name:"教育社区",
        parent:0,
        factor:{id_5:1.00},
    },
    {
        id:10,
        name:"幼儿园学区",
        parent:9,
        factor:{id_17:1.00},
    },
    {
        id:11,
        name:"小学学区",
        parent:9,
        factor:{id_18:1.00},
    },
    {
        id:10,
        name:"中学学区",
        parent:9,
        factor:{id_19:1.00},
    },
    {
        id:11,
        name:"贵族学校",
        parent:9,
        factor:{id_20:1.00},
    },
    {
        id:12,
        name:"周边培训机构",
        parent:9,
        factor:{id_21:1.00},
    },
    {
        id:13,
        name:"区域中心",
        parent:0,
        factor:{id_4:1.00,id_9:1.00,id_10:1.00},
    },
    {
        id:14,
        name:"次新住宅",
        parent:13,
        factor:{id_22:1.00},
    },
    {
        id:15,
        name:"名企制造",
        parent:13,
        factor:{id_23:1.00},
    },
    {
        id:16,
        name:"物业服务好",
        parent:13,
        factor:{id_24:1.00},
    },
    {
        id:17,
        name:"养老居所",
        parent:0,
        factor:{id_12:1.00,id_15:1.00,},
    },
    {
        id:18,
        name:"医疗发达",
        parent:17,
        factor:{id_21:1.00},
    },
    {
        id:19,
        name:"周边配套全",
        parent:17,
        factor:{id_4:1.00},
    },
    {
        id:20,
        name:"临近公园",
        parent:17,
        factor:{id_11:1.00},
    },
    {
        id:21,
        name:"小区环境好",
        parent:17,
        factor:{id_12:1.00},
    },
    {
        id:22,
        name:"投资精选",
        parent:0,
        factor:{id_6:1.00},
    },
    {
        id:23,
        name:"租售比高",
        parent:22,
        factor:{id_32:1.00},
    },
    {
        id:24,
        name:"出售方便",
        parent:22,
        factor:{id_33:1.00},
    },
    {
        id:25,
        name:"升值潜力大",
        parent:22,
        factor:{id_34:1.00},
    },
    {
        id:26,
        name:"宅男腐女",
        parent:0,
        factor:{id_4:1.00},
    },
    {
        id:27,
        name:"厨艺高手",
        parent:22,
        factor:{id_35:1.00},
    },
    {
        id:28,
        name:"外卖VIP",
        parent:22,
        factor:{id_25:1.00},
    },
    {
        id:26,
        name:"小资生活",
        parent:0,
        factor:{id_10:1.00,id_29:1.00,},
    },
    {
        id:27,
        name:"最爱夜生活",
        parent:22,
        factor:{id_10:1.00},
    },
    {
        id:28,
        name:"购物达人",
        parent:22,
        factor:{id_29:1.00},
    },
    {
        id:26,
        name:"居家生活",
        parent:0,
        factor:{id_4:1.00},
    },
    {
        id:27,
        name:"厨艺高手",
        parent:22,
        factor:{id_35:1.00},
    },
    {
        id:28,
        name:"宠物爱好者",
        parent:22,
        factor:{},
    },
    {
        id:26,
        name:"社交达人",
        parent:0,
        factor:{id_10:1.00,id_29:1.00,},
    },
    {
        id:27,
        name:"最爱夜生活",
        parent:26,
        factor:{id_10:1.00},
    },
    {
        id:28,
        name:"最爱旅行",
        parent:26,
        factor:{},
    },
];